name = "vet_arma_difficulty"
prefix = "V29Difficulty"
author = "veteran29"
include = ["./include"]
files = ["mod.cpp"]

exclude = ["*.psd", "*.png", "*.tga"]

keyname = "{{prefix}}_arma_difficulty_{{version}}"
signame = "{{prefix}}_arma_difficulty_{{version}}"
reuse_private_key = false

releasebuild = [
    "!Set_version",
    "@zip",
    "!publish"
]

[scripts]
    [scripts.Set_version]
        steps_windows = [
            "powershell ./tools/Set-Version.ps1 {{version}} '@V29Difficulty'"
        ]
        # show_output = true

    [scripts.publish]
        steps_windows = [
            "powershell ./tools/Publish.ps1 {{version}} 1881268484 '@V29Difficulty'"
        ]
        show_output = true

